### ISSUE TITLE
在.net core 3.1 中使用 NAutowired.Core 自动注入控制器中得的值为null

### ISSUE THREAD

**Issue by wulincheng** [kirov-opensource/NAutowired#11]
namespace Com.macao.electron.Respository.ModelRepository
{
    /// <summary>
    /// 用户数据接口类
    /// </summary>
    [Repository]
    public partial class UserRepository
    {

    }
}

namespace Com.macao.electron.Service
{
 	 /// <summary>
    /// User 业务接口类
    /// </summary>
    public interface IUserService
    {
        string getTest();
    }
}

namespace Com.macao.electron.ServiceImpl
{
 	 /// <summary>
    /// User 业务接口类
    /// </summary>
    [Service]
    public partial class UserServiceImpl:IUserService
    {
        [Autowired]
        private UserRepository UserDao { get; set; }

        public string getTest() {
            return "你好";
        }
}
}

在Startup.cs 配置如下：
 //将控制器注册为服务
            services.AddControllers().AddControllersAsServices();
            services.Replace(ServiceDescriptor.Transient<IControllerActivator, NAutowiredControllerActivator>());
            //使用自动依赖注入并指定已添加特性的程序集
            services.AutoRegisterDependency(new List<string> { "Com.macao.electron.Respository", "Com.macao.electron.Service", "Com.macao.electron.ServiceImpl", "Com.macao.electron" });

namespace Com.macao.electron.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class AuthController : ControllerBase
    {

        //日志
        [Autowired]
        private ILogger<AuthController> _logger { get; set; }

        [Autowired(typeof(UserServiceImpl))]
        private IUserService UserServiceImpl { get; set; }
  }
}

**Comment by FatTigerWang** [comment]
是找到问题了所以关闭了是吗?

**Comment by wulincheng** [comment]
是的，已经找到问题了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: FatTiger<mailto:notifications@github.com>
发送时间: 2020年11月12日 13:50
收件人: kirov-opensource/NAutowired<mailto:NAutowired@noreply.github.com>
抄送: child<mailto:wulincheng02@outlook.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [kirov-opensource/NAutowired] 在.net core 3.1 中使用 NAutowired.Core 自动注入控制器中得的值为null (#11)


是找到问题了所以关闭了是吗?

―
