### ISSUE TITLE
这个项目会一直维护吗？ 能否支持.netstandard2.1 ？

### ISSUE THREAD

**Issue by chenbigit** [kirov-opensource/NAutowired#3]

**Comment by guoyongchang** [comment]
## 会一直维护吗？

> 会的

## .net standard 2.1 支持

> 我们在之前有看`dotnet core 3.0`这块的命名空间下的访问修饰符全部变为`internal`了，所以对第三方实现支持不友好
>我们今晚会继续商讨下这个问题

**Comment by chenbigit** [comment]
AutoRegisterDependency（this IServiceCollection services, IEnumerable<string> assemblies）建议增加一个AutoRegisterDependency（this IServiceCollection services, IEnumerable<Assembly> assemblies），方便直接传程序集。

**Comment by FatTigerWang** [comment]
> AutoRegisterDependency（此IServiceCollection服务，IEnumerable程序集）建议增加一个AutoRegisterDependency（此IServiceCollection服务，IEnumerable程序集），方便直接传程序集。

目前已经支持通过程序集名词注入容器的方式[进阶](https://github.com/kirov-opensource/NAutowired/blob/master/README.md#%E8%BF%9B%E9%98%B6)

**Comment by FatTigerWang** [comment]
> AutoRegisterDependency（this IServiceCollection services, IEnumerable assemblies）建议增加一个AutoRegisterDependency（this IServiceCollection services, IEnumerable assemblies），方便直接传程序集。

目前已经支持通过程序集注入容器的方式，请查看 [进阶](https://github.com/kirov-opensource/NAutowired/blob/master/README.md#%E8%BF%9B%E9%98%B6)

**Comment by chenbigit** [comment]
netcore3.0 支持在计划吗？

**Comment by FatTigerWang** [comment]
> netcore3.0 支持在计划吗？
### 对 `NET Core 3.0` 的支持在计划中
由于 `ASP.NET Core 2.2` 升级到 `ASP.NET Core 3.0`  时，微软修改了一些类的访问修饰符([详情](https://github.com/aspnet/AspNetCore/commit/5a6d438f7bcf9933dccad22f61e7b7075a1f0f1c#diff-ae65b07410e9de5ce3bb552942068993R13))，导致我们暂且没法对 `NET Core 3.0` 提供支持，但是它在我们的计划中.
### 相关Issue 
* [Review pubinternal types made public in 3.0](https://github.com/aspnet/Mvc/issues/8694)

**Comment by FatTigerWang** [comment]
Version 2.0.0 already supports NETStandard 2.1 and NET Core 3.0
