### ISSUE TITLE
NAutowired在.net core控制台下，如何使用AOP，Interceptor实现日志拦截？

### ISSUE THREAD

**Issue by tianmafly** [kirov-opensource/NAutowired#36]
![image](https://user-images.githubusercontent.com/38370307/193177970-fe027f29-b619-4499-8158-66dbf3c9d4b1.png)
.net core控制台下没有生效，是否能够通过[Service]，[Autowried]实现AOP，Interceptor实现日志拦截？

**Comment by FatTigerWang** [comment]
实际上, ASP.NET Core 中的 Filter 也是 ASP.NET Core 框架通过 IoC 还原出的, 因此能够还原出 Filter 的依赖项. 在控制台的情况下, 没有 Filter, 做 AOP 可能需要依赖更强大的 IoC 框架(例如 [Autofac](https://autofac.org)), .NET Core 自带的 IoC 容器是没有钩子对创建实例时之类的情况做 AOP.
