### ISSUE TITLE
读取配置文件问题

### ISSUE THREAD

**Issue by qdesk** [kirov-opensource/NAutowired#8]
nautowired  读取配置文件的值能跟  spring boot 里面一样  只要写个 @value 标签就能读到 里面的值吗

**Comment by FatTigerWang** [comment]
现在使用NAutowired也可以[读取配置文件](https://github.com/kirov-opensource/NAutowired#%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)的
另外被读取的配置需要自己在`Startup.cs`中加入到容器

**Comment by qdesk** [comment]
能给个示例代码看下怎么写吗

**Comment by FatTigerWang** [comment]
[读取配置文件](https://github.com/kirov-opensource/NAutowired#%E8%AF%BB%E5%8F%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
文档已经有写了，有什么不清楚的地方可以提出来

**Comment by qdesk** [comment]
好的
